### ISSUE TITLE
Cut new release that includes #38

### ISSUE THREAD

**Issue by micahhausler** [opencontainers/go-digest#46]
Essentially this request is just for a new tag that includes #38. Go modules won't fetch the license file update because it isn't included in a tagged version.

**Comment by thaJeztah** [comment]
@dmcgowan @vbatts ptal

**Comment by vbatts** [comment]
right on.

This project has some stale maintainers. And looks like it never made a stable release.
Should we just have another RC? or do folks think this project is ready for a v1.0.0?

**Comment by thaJeztah** [comment]
it's been used for quite a while with the current RC in various projects, and no _substantial_ changes since the last rc was tagged; https://github.com/opencontainers/go-digest/compare/v1.0.0-rc1...master

So, my (non binding) opinion is that tagging current master as `v1.0.0` would make sense.

Possible things to check would be the current copyright (which still mentions "docker"); I seem to recall that for some other projects that were donated, the copyright was updated to "the xx-project authors", and a header added to all files (see https://github.com/containerd/containerd/commit/b12c3215a0af92b9244b14c8555fc028b0d1d8c for example)

 IANAL, and don't know if that's desirable to changes (or if any "official" things are needed to change that)?

**Comment by vbatts** [comment]
@caniszczyk What's the process on re-assigning copyright?

**Comment by caniszczyk** [comment]
I'd expect us to simply have copyright header that say "Copyright OCI Contributors"

We don't assign copyright, we would have a very similar policy to what CNCF does for copyright headers: https://github.com/cncf/foundation/blob/master/copyright-notices.md

**Comment by vbatts** [comment]
On 09/01/20 11:24 -0800, Chris Aniszczyk wrote:
>   I'd expect us to simply have copyright header that say "Copyright OCI
>   Contributors"

That's what I was thinking, but the *-spec repos largely have `Copyright
2016 The Linux Foundation`
And should I just prepend the line before the Docker copyright, since
I'm not invalidating the prior claim.

**Comment by vbatts** [comment]
@caniszczyk @thaJeztah https://github.com/opencontainers/go-digest/pull/52 ?

**Comment by vbatts** [comment]
now looking at #54 
So close
